
CREATE TABLE `jjj_test1` (
 `id` int NOT NULL AUTO_INCREMENT,
 PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `jjj_test2` (
 `id` int NOT NULL AUTO_INCREMENT,
 PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `jjj_test3` (
 `id` int NOT NULL AUTO_INCREMENT,
 PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `jjj_test4` (
 `id` int NOT NULL AUTO_INCREMENT,
 PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `j_test1` (
 `id` int NOT NULL AUTO_INCREMENT,
 PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `j_test2` (
 `id` int NOT NULL AUTO_INCREMENT,
 PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `j_test3` (
 `id` int NOT NULL AUTO_INCREMENT,
 PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `j_test4` (
 `id` int NOT NULL AUTO_INCREMENT,
 PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




CREATE TABLE `iii_test1` (
 `id` int NOT NULL AUTO_INCREMENT,
 PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `iii_test2` (
 `id` int NOT NULL AUTO_INCREMENT,
 PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `iii_test3` (
 `id` int NOT NULL AUTO_INCREMENT,
 PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `iii_test4` (
 `id` int NOT NULL AUTO_INCREMENT,
 PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;







